[fix] Fix element selection after reformat headings
storytouch/ep_script_elements pull request #85
Opened 2020-12-01 23:12 UTC by WillianGoncalves

In this commit we fix a problem on selecting the next element after
reformatting a heading with an empty line.

[Card link](https://trello.com/c/k8Gs8fH8/1202-p3-reformatar-cmdctrlr-abre-janela-para-reformatar-elementos)

2020-12-03 13:33 UTC, joassouza requested changes
Cara, tem um ponto que tenho uma dúvida. É bom certificar que não quebra em nada. Quando rodei os testes aqui algumas coisas pareceram quebradas, não sei se é por causa dessa branch ou é plugin desatualizado.

2020-12-03 13:33 UTC, joassouza commented on static/tests/frontend/specs/api-reformat.js
> +  // special case: https://trello.com/c/k8Gs8fH8/1202-p3-reformatar-cmdctrlr-abre-janela-para-reformatar-elementos
isso https://trello.com/c/k8Gs8fH8/1202 já vai dar no card haha

2020-12-03 13:33 UTC, joassouza commented on static/tests/frontend/specs/api-reformat.js
> +  context('when the user tries to change an empty line to another type', function() {
booooa!

2020-12-03 13:33 UTC, joassouza commented on static/js/reformatShortcutHandler.js
> +      // [3] this step involes two scenarios:
segue o comentário de bloco igual ao primeiro

2020-12-03 13:33 UTC, joassouza commented on static/js/reformatShortcutHandler.js
> +reformatShortcutHandler.prototype._handleChangeWithHeading = function(currentLine, newElementType, context) {
Muito bom, cara! Isso aqui está lindamente comentado

2020-12-03 13:33 UTC, joassouza commented on static/js/elementContentCleaner.js
> +    var titleAndSummaryLines = 2; // 2 lines
cara, isso aqui me pareceu bem perigoso. E se tiver mais de um sumário? Se for uma sequência, ato, episódio e for deletar esse código é chamado? Não quebrou nada com isso?

2020-12-03 14:13 UTC, WillianGoncalves commented on static/tests/frontend/specs/api-reformat.js
> +  // special case: https://trello.com/c/k8Gs8fH8/1202-p3-reformatar-cmdctrlr-abre-janela-para-reformatar-elementos
Boa!!

2020-12-07 13:40 UTC, joassouza requested changes
Segue somente uma sugestão. Bom PR

2020-12-07 13:40 UTC, joassouza commented on static/js/elementContentCleaner.js
> +    triggerEventRemoveSceneMark([currentLine], true);
nós esperamos que o heading e SM seja inseparável sempre. Temos inclusive alguns mecanismo que checa isso. Talvez seja mais seguro mudar a `_removeElement` para remover tudo de uma vez só. A única coisa que mudaria seria a função `var intervalToRemove = this._getIntervalToRemove(lineNumberOfSE);` que deveria retornar todo o intervalo. Poderíamos passar aqui uma flag para `removeElement` ou a própria função `removeElement` poderia checar 

``` js
if (heading) {
 // find heading and scene mark intervals to remove
}
```

2020-12-07 13:40 UTC, joassouza commented on static/tests/frontend/specs/api-deleteElement.js
> +  context('when the current line is a heading with a sequence', function() {
ótimo testes!

2020-12-07 17:35 UTC, merged