2551 script styles
storytouch/ep_script_elements pull request #87
Opened 2021-02-01 22:22 UTC by Roger-Siqueira

This PR is related to [Trello Card 2551](https://trello.com/c/m8TDBTLG/2551-ajustes-visuais-texto-livre).

Decrease margin between scene number and heading because text body requires more space now that we've implemented Courier Prime and its font is larger.  
So we had to decrease margins on the left side of script text so the comment icons column doesn't cut the right part of the text.

Also make GENERAL elements to have the same width of actions, and so, show the same 61 characters per line.
Without defined width, even though ACTION and GENERAL looked the same, the General was sending 1 character to the next line.

2021-02-03 19:30 UTC, ingoncalves requested changes

2021-02-03 19:30 UTC, ingoncalves commented on static/css/editor.css
> +}
Aplicar `display: block` nos `spans` vai causar a quebra de linha dentro de uma mesma linha do Etherpad. Um teste simples é alterar a cor de uma palavra. Provavelmente isso já vai ser o suficiente pra quebrar a linha. Vamos ter que pensar em outra abordagem no nível da `div`, e não dos `spans` dentro dela.

2021-02-04 04:56 UTC, Roger-Siqueira commented on static/css/editor.css
> +}
done via https://github.com/storytouch/ep_script_elements/pull/87/commits/1bf93f43640db907be4d7789c35bdaddd94aac17

2021-02-04 11:55 UTC, ingoncalves approved these changes
Acho que agora está correto!
Seria bom verificar as dimensões das linhas (quantidade de caracteres) de todos os elementos que temos no roteiro e comparar com a versão de staging, que está calibrada com o PDF. Se houver mudanças, vamos ter que recalibrar.

2021-02-04 14:18 UTC, merged